/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State of the apply transaction */
        get: operations["applyState"];
        put?: never;
        /** Apply staged configuration with an automatic revert */
        post: operations["applyConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration edits staged but not yet applied */
        get: operations["stagedChanges"];
        put?: never;
        post?: never;
        /** Throw away the staged draft without touching the device */
        delete: operations["discardStaged"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm that the panel survived the change */
        post: operations["confirmApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo the pending change immediately */
        post: operations["revertApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange admin password for a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this device can do, and why not when it cannot */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the full config (includes secrets) */
        get: operations["exportConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import and apply a backup */
        post: operations["importConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live updates: one stream, topics system/apply/error */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/interfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** L3 interfaces as the router's network daemon sees them */
        get: operations["listInterfaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/lan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The local network, its address handout and its clients */
        get: operations["getLAN"];
        /** Stage this router's own address on the local network (does not apply it) */
        put: operations["stageLAN"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/lan/handout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stage the address handout (does not apply it) */
        put: operations["stageHandout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/lan/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stage an address reserved for one device (does not apply it) */
        put: operations["stageReservation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/lan/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Stage the removal of a reserved address (does not apply it) */
        delete: operations["removeReservation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/wan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The uplink, and which rule identified it */
        get: operations["getWAN"];
        /** Stage a new uplink configuration (does not apply it) */
        put: operations["stageWAN"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List nodes with status */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import node(s) from a .conf or subscription */
        post: operations["importNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a node */
        delete: operations["removeNode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active exit to this node */
        post: operations["activateNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fresh status for one node */
        get: operations["nodeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List routing rules */
        get: operations["listRoutes"];
        put?: never;
        /** Add a routing rule */
        post: operations["addRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply the rule set to the OS */
        post: operations["applyRoutes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a routing rule */
        put: operations["updateRoute"];
        post?: never;
        /** Delete a routing rule */
        delete: operations["deleteRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System snapshot for the dashboard */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ping/traceroute from the agent */
        get: operations["diagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CPU/memory/storage history kept in RAM */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe whether traffic goes via tunnel or direct */
        post: operations["probePath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddressHandout: {
            enabled: boolean;
            first?: string;
            last?: string;
            /** Format: int64 */
            leaseSeconds?: number;
        };
        AddressLease: {
            /** Format: int64 */
            expiresSec?: number;
            hostname?: string;
            ip: string;
            mac: string;
        };
        ApplyConfirmInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ApplyConfirmInputBody.json
             */
            readonly $schema?: string;
            /** @description Token returned by POST /apply */
            token: string;
        };
        ApplyEvent: {
            state: components["schemas"]["ApplyState"];
        };
        ApplyOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ApplyOutputBody.json
             */
            readonly $schema?: string;
            detail?: string;
            ok: boolean;
        };
        ApplyState: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ApplyState.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            deadline?: string;
            error?: string;
            phase: string;
            snapshot_id?: string;
            token?: string;
        };
        ApplyTxInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ApplyTxInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Confirmation window in seconds; 0 uses the server default
             */
            timeout_seconds?: number;
        };
        Capability: {
            available: boolean;
            detail?: string;
            reason?: string;
        };
        ChangesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ChangesOutputBody.json
             */
            readonly $schema?: string;
            changes: components["schemas"]["ConfigChange"][] | null;
            dangerous: boolean;
        };
        ConfigChange: {
            dangerous: boolean;
            detail?: string;
            from: string;
            label: string;
            to: string;
        };
        DiagnosticsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/DiagnosticsOutputBody.json
             */
            readonly $schema?: string;
            output: string;
            target: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorEvent: {
            detail: string;
            topic: string;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HandoutConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/HandoutConfig.json
             */
            readonly $schema?: string;
            enabled: boolean;
            first?: string;
            last?: string;
            /** Format: int64 */
            leaseSeconds?: number;
        };
        ImportInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ImportInputBody.json
             */
            readonly $schema?: string;
            /** @description Raw .conf content (kind=awg-config) */
            content?: string;
            /**
             * @description Import source kind
             * @enum {string}
             */
            kind: "awg-config" | "subscription";
            /** @description Subscription URL (kind=subscription) */
            url?: string;
        };
        LANConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LANConfig.json
             */
            readonly $schema?: string;
            address: string;
            netmask: string;
        };
        LANStatus: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LANStatus.json
             */
            readonly $schema?: string;
            handout: components["schemas"]["AddressHandout"];
            interface: components["schemas"]["NetworkInterface"];
            leases?: components["schemas"]["AddressLease"][] | null;
            reserved?: components["schemas"]["ReservedAddress"][] | null;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            /** @description Admin password */
            password: string;
        };
        LoginOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LoginOutputBody.json
             */
            readonly $schema?: string;
            /** @description RFC3339 expiry */
            expiresAt: string;
            /** @description JWT bearer token */
            token: string;
        };
        MetricsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MetricsOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            bufferBytes: number;
            day: components["schemas"]["Sample"][] | null;
            live: components["schemas"]["Sample"][] | null;
        };
        NetworkInterface: {
            device?: string;
            dns?: string[] | null;
            gateway?: string;
            gateway6?: string;
            ipv4?: string[] | null;
            ipv6?: string[] | null;
            name: string;
            proto?: string;
            up: boolean;
            /** Format: int64 */
            uptimeSec?: number;
        };
        Node: {
            endpoint: string;
            engine: string;
            id: string;
            name: string;
        };
        NodeStatus: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/NodeStatus.json
             */
            readonly $schema?: string;
            active: boolean;
            /** Format: int64 */
            handshakeAgeSec: number;
            lastError?: string;
            nodeId: string;
            /** Format: int64 */
            rxBytes: number;
            /** Format: int64 */
            txBytes: number;
        };
        NodeWithStatus: {
            node: components["schemas"]["Node"];
            status?: components["schemas"]["NodeStatus"];
        };
        PathProbe: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/PathProbe.json
             */
            readonly $schema?: string;
            actualVia: string;
            detail?: string;
            expectedVia: string;
            ok: boolean;
            target: string;
        };
        ProbeInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ProbeInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Expected path
             * @enum {string}
             */
            expectedVia: "tunnel" | "direct";
            /** @description Domain or IP to test */
            target: string;
        };
        ReservationConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ReservationConfig.json
             */
            readonly $schema?: string;
            ip: string;
            mac: string;
            name?: string;
        };
        ReservedAddress: {
            id?: string;
            ip: string;
            mac: string;
            name?: string;
        };
        RouteRule: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/RouteRule.json
             */
            readonly $schema?: string;
            id: string;
            kind: string;
            note?: string;
            target: string;
            value: string;
        };
        RuleBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/RuleBody.json
             */
            readonly $schema?: string;
            /**
             * @description Match kind
             * @enum {string}
             */
            kind: "domain" | "subnet";
            /** @description User comment */
            note?: string;
            /**
             * @description Where to send it
             * @enum {string}
             */
            target: "tunnel" | "direct";
            /** @description Domain or CIDR */
            value: string;
        };
        Sample: {
            /** Format: int64 */
            at: number;
            /** Format: double */
            cpuPercent: number;
            /** Format: int64 */
            memTotal: number;
            /** Format: int64 */
            memUsed: number;
            /** Format: int64 */
            storageUsed: number;
        };
        SystemEvent: {
            sample: components["schemas"]["Sample"];
            system: components["schemas"]["SystemInfo"];
        };
        SystemInfo: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SystemInfo.json
             */
            readonly $schema?: string;
            /** Format: double */
            cpuPercent: number;
            egressGeo?: string;
            egressIP?: string;
            firmware?: string;
            hostname: string;
            kernel?: string;
            loadAvg: number[] | null;
            /** Format: int64 */
            memTotal: number;
            /** Format: int64 */
            memUsed: number;
            model?: string;
            platform: string;
            /** Format: int64 */
            storageTotal?: number;
            /** Format: int64 */
            storageUsed?: number;
            tunnelEngine?: string;
            tunnelUp: boolean;
            /** Format: int64 */
            uptimeSec: number;
            wanIP?: string;
        };
        WANConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/WANConfig.json
             */
            readonly $schema?: string;
            address?: string;
            dns?: string[] | null;
            gateway?: string;
            interface?: string;
            netmask?: string;
            password?: string;
            proto: string;
            username?: string;
        };
        WANStatus: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/WANStatus.json
             */
            readonly $schema?: string;
            candidates?: string[] | null;
            interface: components["schemas"]["NetworkInterface"];
            selectedBy: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applyState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyState"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    applyConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyTxInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyState"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    stagedChanges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    discardStaged: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    confirmApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyConfirmInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyState"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    revertApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyState"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Capability"];
                    };
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    exportConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    importConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["ApplyEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "apply";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["ErrorEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "error";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["SystemEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "system";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listInterfaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkInterface"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getLAN: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LANStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    stageLAN: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LANConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    stageHandout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoutConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    stageReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    removeReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Reservation entry as reported by GET /network/lan */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getWAN: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WANStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    stageWAN: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WANConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeWithStatus"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    importNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    removeNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    activateNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    nodeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteRule"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    addRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteRule"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    applyRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    updateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteRule"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    diagnostics: {
        parameters: {
            query?: {
                /** @description Host or IP to diagnose */
                target?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    probePath: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathProbe"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
