// Package routing renders VeilBridge's selective-routing rules to nftables and
// applies them. v0.1 is static (domain/subnet → tunnel|direct), no FakeIP — that
// arrives with the DNS milestone M6 (D-7). The generator is engine-agnostic; only the
// transparent-forwarding behaviour differs by engine (see note below).
//
// Engine caveat (DESIGN §5.2): with the kernel engine these marks/routes
// transparently forward LAN traffic into the tunnel interface. With the
// userspace netstack engine there is no transit forwarding yet — the rendered
// ruleset is a correct declaration of intent, but the agent's own out-of-tunnel
// traffic still needs the engine Dialer. Full userspace transit is not built yet.
package routing

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"github.com/veilbridge-os/veilbridge/internal/core"
)

// TableName is the nftables table VeilBridge owns. It is flushed and rewritten
// wholesale on each Apply, so the operation is idempotent.
const TableName = "veilbridge"

// fwmark tags packets destined for the tunnel. The kernel engine's interface is
// pointed at by an ip rule on this mark (set up by the OS adapter, not here).
const TunnelMark = "0x1"

// Generator renders a rule set to an `nft -f` script. It holds no state; the
// rule set is passed in so callers (adapters) own persistence.
type Generator struct {
	// TunnelIface is the name of the tunnel interface marks route to. Empty is
	// allowed (e.g. userspace v0.1) — the script then only marks, no oif rule.
	TunnelIface string
}

// Render produces a complete, idempotent `nft -f` script for the given rules.
// Subnet rules go into named sets directly; domain rules are emitted as comments
// listing the domains (v0.1 has no DNS-driven set population — that is the FakeIP
// work in M6). The script always starts by deleting any existing table so a
// re-apply fully replaces prior state.
func (g Generator) Render(rules []core.RouteRule) (string, error) {
	tunnelV4, tunnelV6, directV4, directV6, domains, err := classify(rules)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	// Idempotent reset: `add` creates the table if absent so the following
	// `delete` always succeeds (even on first run), then recreate it fresh.
	fmt.Fprintf(&b, "#!/usr/sbin/nft -f\n")
	fmt.Fprintf(&b, "# Generated by VeilBridge routing — do not edit by hand.\n")
	fmt.Fprintf(&b, "add table inet %s\n", TableName)
	fmt.Fprintf(&b, "delete table inet %s\n", TableName)
	fmt.Fprintf(&b, "table inet %s {\n", TableName)

	writeSet(&b, "tunnel4", "ipv4_addr", tunnelV4)
	writeSet(&b, "tunnel6", "ipv6_addr", tunnelV6)
	writeSet(&b, "direct4", "ipv4_addr", directV4)
	writeSet(&b, "direct6", "ipv6_addr", directV6)

	// Mangle chain: mark tunnel-bound traffic. Direct sets are matched first so
	// an explicit direct rule wins over an overlapping tunnel rule.
	fmt.Fprintf(&b, "  chain prerouting {\n")
	fmt.Fprintf(&b, "    type filter hook prerouting priority mangle; policy accept;\n")
	if len(directV4) > 0 {
		fmt.Fprintf(&b, "    ip daddr @direct4 return\n")
	}
	if len(directV6) > 0 {
		fmt.Fprintf(&b, "    ip6 daddr @direct6 return\n")
	}
	if len(tunnelV4) > 0 {
		fmt.Fprintf(&b, "    ip daddr @tunnel4 meta mark set %s\n", TunnelMark)
	}
	if len(tunnelV6) > 0 {
		fmt.Fprintf(&b, "    ip6 daddr @tunnel6 meta mark set %s\n", TunnelMark)
	}
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "}\n")

	// Domain rules are recorded as comments in v0.1 (no DNS-set population yet).
	if len(domains) > 0 {
		fmt.Fprintf(&b, "# domain rules (not yet enforced — needs FakeIP, roadmap M6):\n")
		for _, d := range domains {
			fmt.Fprintf(&b, "#   %s -> %s\n", d.Value, d.Target)
		}
	}
	return b.String(), nil
}

type domainRule struct {
	Value  string
	Target core.Target
}

// classify validates rules and splits them into nft sets by family and target,
// plus the domain list. Invalid CIDRs are a hard error (caught before apply).
func classify(rules []core.RouteRule) (t4, t6, d4, d6 []string, domains []domainRule, err error) {
	for _, r := range rules {
		switch r.Kind {
		case core.RuleSubnet:
			p, perr := netip.ParsePrefix(strings.TrimSpace(r.Value))
			if perr != nil {
				return nil, nil, nil, nil, nil, fmt.Errorf("routing: bad subnet %q: %w", r.Value, perr)
			}
			tunnel := r.Target == core.TargetTunnel
			switch {
			case p.Addr().Is4() && tunnel:
				t4 = append(t4, p.String())
			case p.Addr().Is4():
				d4 = append(d4, p.String())
			case tunnel:
				t6 = append(t6, p.String())
			default:
				d6 = append(d6, p.String())
			}
		case core.RuleDomain:
			if strings.TrimSpace(r.Value) == "" {
				return nil, nil, nil, nil, nil, fmt.Errorf("routing: empty domain value")
			}
			domains = append(domains, domainRule{Value: r.Value, Target: r.Target})
		default:
			return nil, nil, nil, nil, nil, fmt.Errorf("routing: unknown rule kind %q", r.Kind)
		}
	}
	// Stable output for deterministic, diffable scripts.
	sort.Strings(t4)
	sort.Strings(t6)
	sort.Strings(d4)
	sort.Strings(d6)
	sort.Slice(domains, func(i, j int) bool { return domains[i].Value < domains[j].Value })
	return t4, t6, d4, d6, domains, nil
}

func writeSet(b *strings.Builder, name, typ string, elems []string) {
	fmt.Fprintf(b, "  set %s { type %s; flags interval;", name, typ)
	if len(elems) > 0 {
		fmt.Fprintf(b, " elements = { %s };", strings.Join(elems, ", "))
	}
	fmt.Fprintf(b, " }\n")
}
